version: "3.8"

services:
  task_a:
    build:
      context: ./app/task_a
      dockerfile: Dockerfile
    container_name: dsn-bct-task-a
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8001
      - GOOGLE_API_KEY_1=${GOOGLE_API_KEY_1}
      - GOOGLE_API_KEY_2=${GOOGLE_API_KEY_2}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}

    restart: unless-stopped

  task_b:
    build:
      context: ./app/task_b
      dockerfile: Dockerfile
    container_name: dsn-bct-task-b
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8002
      - GOOGLE_API_KEY_1=${GOOGLE_API_KEY_1}
      - GOOGLE_API_KEY_2=${GOOGLE_API_KEY_2}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}

    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: dsn-bct-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - task_a
      - task_b
    restart: unless-stopped

networks:
  default:
    name: dsn-bct-network
